name: Pipeline de Integración Continua(CI)
on:
  push:
    branches: ["main", "master", "feature/adiciona-ci"] # Adicionei sua branch aqui para o teste rodar direto no push
  pull_request:
    branches:  ["main", "master"]
jobs:
  testes-e-validacao:
    runs-on: ubuntu-latest
    steps: # Agora os steps estão bem abaixo do job correspondente
      - name: Baixar o código-fonte
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Corrigido de docker/setup-node para actions/setup-node
        with:
          node-version: '20'
          cache: "npm"
      - name: Instalar dependências
        run: npm ci
      - name: Executar Linter
        run: npm run lint
      - name: Executar Testes Automatizados
        run: npm test
      - name: Verificação de Segurança de Dependências (SAST)
        run: npm audit --audit-level=high
